server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alexa
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
    password: communityserver
